# Generated by Django 4.1.7 on 2023-03-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='validacao',
            field=models.BooleanField(default=False, max_length=255, verbose_name='Validação'),
        ),
    ]
